package dafitiafil.parse.callback;

import dafitiafil.parse.callback.basico.CategoriaProdutoProdutoDetalheCallbackHtmlBase;

public class CategoriaProdutoProdutoDetalheCallbackHtml extends CategoriaProdutoProdutoDetalheCallbackHtmlBase{



}