package coletapreco.regracolecao.impl;

import coletapreco.regracolecao.OportunidadeInteresseClienteRegraColecao;

public class OportunidadeInteresseClienteRegraColecaoImpl extends OportunidadeInteresseClienteRegraColecao {

}
